### ISSUE TITLE
New bedrock ore system not working.

### ISSUE THREAD

**Issue by Mixersat** [JameH2/Hbm-s-Nuclear-Tech-GIT#187] opened 2024-12-20 17:48 UTC
The new bedrock ore processing system works but the raw bedrock ore are not generated in the world, the recipes for the raw bedrock and density scanner do not appear in the NEI menu even if the B:2 config is true.

**Comment by quindao** [comment] 2024-12-21 15:43
this is a duplicate of #99 in which it is stated that the world gen is currently disabled pending a balance pass to make the new BRO system integrate with the space stuff

**Closed as completed** 2024-12-21 19:19 UTC
